version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tuum
      - SPRING_DATASOURCE_USERNAME=tuum
      - SPRING_DATASOURCE_PASSWORD=tuum
      - SPRING_JPA_HIBERNATE_DDL_AUTO=auto
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      
  rabbitmq-container:
    image: rabbitmq:3-management
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
        - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      
      